### ISSUE TITLE
Incorrect shape for 'image_mask' when trying to load Inscopix-CNMFe

### ISSUE THREAD

**Issue by MicTott** [pynapple-org/pynapple#120] opened 2023-01-06 14:37 UTC
I've been playing around with Pynapple and really loving it - so first off, thanks for developing this! 

I'm currently trying to import some 1p calcium imaging data from inscopix and having issues. The data has been preprocessed, filtered, motion corrected, and cell identified via Inscopix's implementation of CNMFe. From there, I've exported the cell traces (as *_traces.csv) and both the cell map and cell images. 

When trying to load the data, I keep getting the error below. Any idea what might be causing this issue? 

> File ~/Documents/Inscopix_Projects/MT_S1prism_test/MT_S1_prism_test.py:21 in <module>
>     data = nap.load_session(str(data_path), 'inscopix-cnmfe')
> 
>   File ~/opt/anaconda3/lib/python3.9/site-packages/pynapple/io/misc.py:64 in load_session
>     return InscopixCNMFE(path)
> 
>   File ~/opt/anaconda3/lib/python3.9/site-packages/pynapple/io/cnmfe.py:493 in __init__
>     self.save_cnmfe_nwb(path)
> 
>   File ~/opt/anaconda3/lib/python3.9/site-packages/pynapple/io/cnmfe.py:597 in save_cnmfe_nwb
>     ps.add_roi(image_mask=image_mask)
> 
>   File ~/opt/anaconda3/lib/python3.9/site-packages/hdmf/utils.py:644 in func_call
>     pargs = _check_args(args, kwargs)
> 
>   File ~/opt/anaconda3/lib/python3.9/site-packages/hdmf/utils.py:637 in _check_args
>     raise ExceptionType(msg)
> 
> ValueError: PlaneSegmentation.add_roi: incorrect shape for 'image_mask' (got '(227,)', expected '[[None, None], [None, None, None]]')

**Comment by gviejo** [comment] 2023-01-06 21:46
Hi Michael, 

Thanks for testing it out. It looks like a NWB problem here. 
Could you send me a very small dataset processed with inscopix-cnmfe that can reproduce the error? 

If it's too complicated and you don't care about NWB, you can use the function load_inscopix_cnmfe from the io directly like this :

```python
import pandas as pd
import tifffile as tiff
import pynapple as nap

def load_inscopix_cnmfe(path, sampling_rate=30.0):
        """
        Load the calcium transients and the spatial footprints.
        Parameters
        ----------
        path : str
            Path to the session
       sampling_rate: float
           Sampling rate of the session
        """
        files = os.listdir(path)
        tracefile = [f for f in files if f.endswith("_traces.csv")]

        if len(tracefile):
            C = pd.read_csv(os.path.join(path, tracefile[0]), index_col=0)
        else:
            raise RuntimeError(
                "Path {} does not contain the file {}".format(path, "*_traces.csv")
            )

        time_index = np.arange(0, len(C)) / sampling_rate

        C = nap.TsdFrame(t=time_index, d=C.values)

        tifffile = [f for f in files if f.endswith(".tiff")]
        if len(tifffile):
            A = tiff.imread(os.path.join(path, tifffile[0]))
        else:
            raise RuntimeError(
                "Path {} does not contain the file {}".format(path, "*.tiff")
            )

        return A, C
```

**Comment by gviejo** [comment] 2024-02-13 23:16
The inscopix-cnmfe loader has been removed from pynapple. Closing this.

**Closed by gviejo** 2024-02-13 23:16 UTC
