### ISSUE TITLE
'Category' tags for TsGroup must be array

### ISSUE THREAD

**Issue by isabelgaron** [pynapple-org/pynapple#247] opened 2024-03-21 18:17 UTC
Pynapple ignores/does not raise issue when passed a list instead of an array for tsgroup tags

**Comment by gviejo** [comment] 2024-03-29 14:47
I can't reproduce this error. If I do 

```python
import pynapple as nap
import numpy as np
group =   {
            0: nap.Ts(t=np.arange(10)),
            1: nap.Ts(t=np.arange(20)),
            2: nap.Ts(t=np.arange(30))
           }
tsgroup = nap.TsGroup(group, a  = [0, 1, 2])

tsgroup.set_info(b=[3,4,5])
```
I get  
```python
  Index    rate    a    b
-------  ------  ---  ---
      0    0.34    0    3
      1    0.69    1    4
      2    1.03    2    5
```
Can you paste the error you got more in details?

**Comment by gviejo** [comment] 2024-03-29 16:15
thanks closing this

**Closed by gviejo** 2024-03-29 16:15 UTC
